"""Voice lines and sound effects for the campaign, generated by ElevenLabs.

The script is audio/lines.csv, the cast is audio/voices.json and the sound effects are audio/sfx.csv. Output goes to
audio/voice/ and audio/sfx/.

    python audio/gen_voices.py --dry-run          # no key needed: checks everything, lists what would be generated or polished
    python audio/gen_voices.py --my-voices        # lists the voices in your ElevenLabs account with their IDs
    python audio/gen_voices.py --check            # checks the key, each cast voice and the characters left on the account
    python audio/gen_voices.py                    # generates every line and sound whose text, voice or settings changed
    python audio/gen_voices.py --only C01 Q01     # just these scenes, speakers, line or sound ids (e.g. --only clown sfx)
    python audio/gen_voices.py --force --only miranda
    python audio/gen_voices.py --manifest-only    # rewrites the manifests from the files already on disk
    python audio/gen_voices.py --adopt --only H_TITLE   # an mp3 made in the ElevenLabs app counts as up to date
    python audio/gen_voices.py --prune            # deletes mp3s whose line or sound is no longer in the bank
    python audio/gen_voices.py --polish-only      # no key: applies polish changes that need no new take, skips the rest

The API key comes from ELEVENLABS_API_KEY in the environment or in .env at the repo root (never commit it). Voice IDs are not
secret and live in voices.json, so the whole team generates the same cast. A speaker without a voice ID is skipped.

Square brackets in a line are ElevenLabs v3 audio tags ([sighs], [hiccups]): spoken as direction, stripped from captions, and
stripped from the text too if a non-v3 model is chosen (older models would read them out loud). A line's `stability` column
overrides its speaker's (v3: 0.0 creative, 0.5 natural, 1.0 robust); its `sfx` column names a sound to play just before it.

Polish (needs ffmpeg: `pip install imageio-ffmpeg`, or ffmpeg on the PATH): a speaker's `tempo` speeds the take up without
changing pitch, `max_pause` shortens long silences and `level` evens out loudness (the speech's level in dB, peaks kept below
-1 dBFS); a sound's `volume_db` sets its level, and sounds are made mono so none can hint at a side. Polish is applied once to
the raw take and recorded, so it never compounds. A change of `level` or `volume_db` is applied to the polished take in place,
for free. The raw takes this machine generated are kept in a git-ignored `.raw/` folder, so a new `tempo` or `max_pause` is
free here too; anywhere else it means a new take.

Output: voice/<id>.mp3 and sfx/<id>.mp3, plus manifest.json in each folder (voice: story order with id, scene, panel, branch,
speaker, caption, sfx cue and file; sfx: id, when to play, loop) for Godot and the server, and manifest.js (the same data)
so table_read.html works when opened straight from disk.
"""

from __future__ import annotations

import argparse
import csv
import hashlib
import json
import os
import re
import shutil
import subprocess
import sys
import threading
import time
from concurrent.futures import ThreadPoolExecutor, as_completed
from dataclasses import dataclass
from pathlib import Path

AUDIO = Path(__file__).resolve().parent
ROOT = AUDIO.parent
LINES_CSV = AUDIO / "lines.csv"
VOICES_JSON = AUDIO / "voices.json"
SFX_CSV = AUDIO / "sfx.csv"
OUT_DIR = AUDIO / "voice"
SFX_DIR = AUDIO / "sfx"
SFX_MODEL = "eleven_text_to_sound_v2"

TAG = re.compile(r"\[[^\[\]]*\]")
ID_OK = re.compile(r"^[A-Z0-9_]+$")  # ids double as file names and Godot resource paths
VOICE_ID = re.compile(r"(?<![A-Za-z0-9])[A-Za-z0-9]{20}(?![A-Za-z0-9])")  # ElevenLabs voice IDs are 20 characters
BRANCHES = {"", "correct", "wrong", "giant_win", "giant_loss", "father_win", "father_loss"}
V3_STABILITY = {0.0, 0.5, 1.0}
RETRY_STATUS = {429, 500, 502, 503, 504}
RETRIES = 4
SR = 44100
SILENCE_DB = -42.0  # quieter than this counts as a pause when max_pause trims them
MAX_LIMIT_DB = 8.0  # how far `level` may push a sharp peak into the limiter to bring the rest of a line up


@dataclass(frozen=True)
class Line:
    id: str
    scene: str
    panel: str
    branch: str
    speaker: str
    line: str
    note: str
    stability: str = ""
    sfx: str = ""

    @property
    def caption(self) -> str:
        return caption(self.line)


@dataclass(frozen=True)
class Sound:
    id: str
    prompt: str
    seconds: str
    loop: str
    volume_db: str
    when: str
    note: str = ""


def caption(text: str) -> str:
    """The text players read: audio tags removed, spacing tidied."""
    return re.sub(r"\s{2,}", " ", TAG.sub("", text)).strip()


def spoken_text(line: Line, model: str) -> str:
    """What is sent to ElevenLabs. Only the v3 models understand audio tags."""
    return line.line.strip() if model.startswith("eleven_v3") else line.caption


def voice_id_from(value: str) -> str:
    """Accepts a bare voice ID or a link that contains one (voice library or share links); '' if there isn't one."""
    value = (value or "").strip()
    found = VOICE_ID.findall(value)
    return found[-1] if found else ""


def _read_csv(path: Path, cls):
    with path.open(newline="", encoding="utf-8") as f:
        return [cls(**{k: (row.get(k) or "").strip() for k in cls.__dataclass_fields__}) for row in csv.DictReader(f)]


def load_lines(path: Path = LINES_CSV) -> list[Line]:
    return _read_csv(path, Line)


def load_sounds(path: Path = SFX_CSV) -> list[Sound]:
    return _read_csv(path, Sound) if path.exists() else []


def load_cast(path: Path = VOICES_JSON) -> dict:
    return json.loads(path.read_text(encoding="utf-8"))


def stability_for(line: Line, speaker: dict) -> float | None:
    return float(line.stability) if line.stability else speaker.get("stability")


def voice_post(speaker: dict) -> str:
    """The polish a speaker's takes get, as a short key recorded in the manifest ('' = none)."""
    tempo, pause, level = float(speaker.get("tempo") or 1.0), speaker.get("max_pause"), speaker.get("level")
    parts = [] if tempo == 1.0 and not pause else [f"tempo={tempo:g},max_pause={float(pause or 0):g}"]
    return ",".join(parts + ([f"level={float(level):g}"] if level is not None else []))


def sound_post(sound: Sound) -> str:
    return f"mono,volume_db={float(sound.volume_db or 0):g}"


IN_PLACE = {"volume_db", "level"}  # re-applied to a polished take, these give the same result as polishing the raw take


def _post_items(post: str) -> dict[str, str]:
    return dict(p.partition("=")[::2] for p in post.split(",") if p)


def in_place(have: str, want: str) -> dict | None:
    """How to turn a take polished as `have` into one polished as `want` without its raw take: a volume step or a new
    speech level. None when that isn't possible (nothing was polished yet, or tempo or pauses changed)."""
    a, b = _post_items(have), _post_items(want)
    if not have or a == b or ("level" in a and "level" not in b):
        return None
    if {k: v for k, v in a.items() if k not in IN_PLACE} != {k: v for k, v in b.items() if k not in IN_PLACE}:
        return None
    return {"volume_db": float(b.get("volume_db") or 0) - float(a.get("volume_db") or 0),
            "level": float(b["level"]) if "level" in b else None}


def raw_path(path: Path, h: str) -> Path:
    """Where this machine keeps the unpolished take (git-ignored), so later polish changes need no new take."""
    return path.parent / ".raw" / f"{path.stem}-{h}.mp3"


def problems(lines: list[Line], cast: dict, sounds: list[Sound] | None = None) -> list[str]:
    """Everything that would make a line or sound unplayable or wrong. Empty means the banks are sound."""
    out: list[str] = []
    speakers = cast.get("speakers", {})
    sounds = sounds or []
    sound_ids = {s.id for s in sounds}
    seen: set[str] = set()
    for ln in lines:
        where = ln.id or "(row without an id)"
        if not ID_OK.match(ln.id):
            out.append(f"{where}: ids use A-Z, 0-9 and _ only")
        if ln.id in seen:
            out.append(f"{where}: duplicate id")
        seen.add(ln.id)
        if ln.speaker not in speakers:
            out.append(f"{where}: speaker '{ln.speaker}' is not in voices.json")
        if ln.branch not in BRANCHES:
            out.append(f"{where}: unknown branch '{ln.branch}'")
        if ln.line.count("[") != ln.line.count("]"):
            out.append(f"{where}: unbalanced [ ]")
        if not ln.caption:
            out.append(f"{where}: no text")
        if ln.stability and (not re.fullmatch(r"[01](\.\d+)?", ln.stability) or float(ln.stability) not in V3_STABILITY):
            out.append(f"{where}: stability must be 0.0, 0.5 or 1.0 for eleven_v3")
        if ln.sfx and ln.sfx not in sound_ids:
            out.append(f"{where}: sfx '{ln.sfx}' is not in sfx.csv")
    for s in sounds:
        where = s.id or "(sound without an id)"
        if not ID_OK.match(s.id):
            out.append(f"{where}: ids use A-Z, 0-9 and _ only")
        if s.id in seen:
            out.append(f"{where}: duplicate id")
        seen.add(s.id)
        try:
            if not 0.5 <= float(s.seconds) <= 30:
                out.append(f"{where}: seconds must be 0.5 to 30")
            float(s.volume_db or 0)
        except ValueError:
            out.append(f"{where}: seconds and volume_db must be numbers")
        if s.loop not in ("", "yes", "no"):
            out.append(f"{where}: loop is yes or no")
        if not s.prompt:
            out.append(f"{where}: no prompt")
    return out


def line_hash(line: Line, speaker: dict, model: str, output_format: str) -> str:
    """Changes when anything the API is sent changes, so unchanged lines are never paid for twice. Polish isn't in it."""
    key = [spoken_text(line, model), voice_id_from(speaker.get("voice_id", "")), stability_for(line, speaker), model,
           output_format]
    return hashlib.sha256(json.dumps(key).encode()).hexdigest()[:16]


def sound_hash(sound: Sound, output_format: str) -> str:
    key = [sound.prompt, float(sound.seconds), sound.loop == "yes", SFX_MODEL, output_format]
    return hashlib.sha256(json.dumps(key).encode()).hexdigest()[:16]


def read_manifest(out_dir: Path, key: str = "lines") -> dict[str, dict]:
    path = out_dir / "manifest.json"
    if not path.exists():
        return {}
    try:
        return {e["id"]: e for e in json.loads(path.read_text(encoding="utf-8")).get(key, [])}
    except (ValueError, KeyError, TypeError):
        return {}


def _write(out_dir: Path, head: dict, key: str, entries: list[dict], js_name: str) -> None:
    out_dir.mkdir(parents=True, exist_ok=True)
    one = lambda v: json.dumps(v, ensure_ascii=False)  # noqa: E731
    fields = "".join(f"{one(k)}: {one(v)},\n " for k, v in head.items())
    text = '{%s%s: [\n  %s\n ]}' % (fields, one(key), ",\n  ".join(one(e) for e in entries))  # a line per entry
    (out_dir / "manifest.json").write_text(text + "\n", encoding="utf-8")
    (out_dir / "manifest.js").write_text(
        "// Written by audio/gen_voices.py for table_read.html (browsers block fetch() from file://).\n"
        f"window.{js_name} = {text};\n", encoding="utf-8")


def write_manifest(lines: list[Line], cast: dict, out_dir: Path, hashes: dict[str, str],
                   posts: dict[str, str] | None = None, model: str = "") -> dict:
    """Story-ordered index of every line; `file` is null until its mp3 exists, and `stale` marks an mp3 made from an
    older version of the line (a known hash that no longer matches)."""
    speakers, posts = cast.get("speakers", {}), posts or {}
    model, fmt = model or cast.get("model", "eleven_v3"), cast.get("output_format", "mp3_44100_128")
    entries = []
    for ln in lines:
        have = (out_dir / f"{ln.id}.mp3").exists()
        h = hashes.get(ln.id) if have else None
        entries.append({
            "id": ln.id, "scene": ln.scene, "panel": ln.panel, "branch": ln.branch,
            "speaker": ln.speaker, "name": speakers.get(ln.speaker, {}).get("name", ln.speaker),
            "caption": ln.caption, "sfx": ln.sfx or None,
            "file": f"{ln.id}.mp3" if have else None, "hash": h, "post": posts.get(ln.id, "") if have else "",
            "stale": bool(h) and h != line_hash(ln, speakers.get(ln.speaker, {}), model, fmt),
        })
    head = {"model": cast.get("model", ""), "speakers": {k: v.get("name", k) for k, v in speakers.items()}}
    _write(out_dir, head, "lines", entries, "VOICE_MANIFEST")
    return {**head, "lines": entries}


def write_sfx_manifest(sounds: list[Sound], out_dir: Path, hashes: dict[str, str], posts: dict[str, str],
                       fmt: str = "mp3_44100_128") -> None:
    entries = []
    for s in sounds:
        have = (out_dir / f"{s.id}.mp3").exists()
        h = hashes.get(s.id) if have else None
        entries.append({"id": s.id, "when": s.when, "loop": s.loop == "yes", "file": f"{s.id}.mp3" if have else None,
                        "hash": h, "post": posts.get(s.id, "") if have else "",
                        "stale": bool(h) and h != sound_hash(s, fmt)})
    _write(out_dir, {"model": SFX_MODEL}, "sounds", entries, "SFX_MANIFEST")


def _ffmpeg() -> str | None:
    try:
        import imageio_ffmpeg
        return imageio_ffmpeg.get_ffmpeg_exe()
    except Exception:
        return shutil.which("ffmpeg")


def _window_db(x, n: int = SR // 100):
    """Level of each 10 ms window, in dB."""
    import numpy as np

    frames = len(x) // n
    return 20 * np.log10(np.sqrt((x[:frames * n].reshape(frames, n) ** 2).mean(1)) + 1e-9)


def speech_db(x) -> float | None:
    """Loudness of the speech in a take (pauses left out), in dB. None for silence."""
    import numpy as np

    db = _window_db(x)
    active = db[db >= SILENCE_DB]
    return float(10 * np.log10((10 ** (active / 10)).mean())) if len(active) else None


def polish(path: Path, tempo: float = 1.0, max_pause: float | None = None, volume_db: float = 0.0,
           level: float | None = None) -> None:
    """Rewrites an mp3 in place: mono, long pauses shortened to max_pause, speech brought to `level` dB (peaks kept below
    -1 dBFS), tempo without a pitch change, volume."""
    import numpy as np

    ff = _ffmpeg()
    if not ff:
        raise RuntimeError("ffmpeg not found: pip install imageio-ffmpeg")
    raw = subprocess.run([ff, "-v", "error", "-i", str(path), "-ac", "1", "-ar", str(SR), "-f", "f32le", "-"],
                         capture_output=True, check=True).stdout
    x = np.frombuffer(raw, np.float32)
    if max_pause:
        n = SR // 100  # 10 ms windows
        frames = len(x) // n
        loud = _window_db(x, n) >= SILENCE_DB
        keep, half, i = np.ones(len(x), bool), int(SR * max_pause / 2), 0
        while i < frames:
            j = i
            while j < frames and not loud[j]:
                j += 1
            if j > i and (j - i) * n > 2 * half:
                keep[i * n + half:j * n - half] = False  # keep half the allowed pause on each side of the cut
            i = j + 1 if j == i else j
        x = x[keep]
    filters = []
    if level is not None and (now := speech_db(x)) is not None:
        peak = 20 * np.log10(float(np.abs(x).max()) + 1e-9)
        gain = min(level - now, -1.0 - peak + MAX_LIMIT_DB)  # a hiccup or a shout may be limited, by at most MAX_LIMIT_DB
        x = x * np.float32(10 ** (gain / 20))
        if peak + gain > -1.0:
            filters.append("alimiter=limit=0.891:attack=2:release=50:level=0")  # peaks stay below -1 dBFS
    filters += [f"atempo={tempo:g}"] if tempo != 1.0 else []
    if volume_db:
        filters.append(f"volume={volume_db:g}dB")
    tmp = path.with_name(f".{path.name}.polish.mp3")
    cmd = [ff, "-v", "error", "-y", "-f", "f32le", "-ar", str(SR), "-ac", "1", "-i", "-"]
    cmd += (["-af", ",".join(filters)] if filters else []) + ["-c:a", "libmp3lame", "-b:a", "128k", str(tmp)]
    subprocess.run(cmd, input=np.ascontiguousarray(x).tobytes(), check=True)
    os.replace(tmp, path)


def polish_line(path: Path, speaker: dict) -> None:
    level = speaker.get("level")
    polish(path, float(speaker.get("tempo") or 1.0), speaker.get("max_pause"),
           level=float(level) if level is not None else None)


def polish_sound(path: Path, sound: Sound) -> None:
    polish(path, volume_db=float(sound.volume_db or 0))


def _api_detail(err: Exception) -> tuple[int, str, str]:
    """(HTTP status, ElevenLabs status code such as 'voice_not_found', message) from an SDK error."""
    status = getattr(err, "status_code", None) or 0
    body = getattr(err, "body", None)
    detail = body.get("detail") if isinstance(body, dict) else None
    if isinstance(detail, dict):
        return status, str(detail.get("status") or detail.get("code") or ""), str(detail.get("message") or detail)
    return status, "", str(detail or body or err)


def _client():
    try:
        from dotenv import load_dotenv
        load_dotenv(ROOT / ".env")
    except ImportError:
        pass
    key = os.environ.get("ELEVENLABS_API_KEY", "").strip()
    if not key:
        sys.exit("ELEVENLABS_API_KEY is not set. Put it in .env at the repo root (see .env.example) or export it.")
    try:
        from elevenlabs.client import ElevenLabs
    except ImportError:
        sys.exit("The elevenlabs package is missing: pip install -r requirements.txt")
    return ElevenLabs(api_key=key)


def _with_retries(call):
    for attempt in range(RETRIES):
        try:
            return b"".join(call())
        except Exception as err:  # the SDK's ApiError, or a network error from httpx underneath it
            import httpx

            status, _, _ = _api_detail(err)
            transient = status in RETRY_STATUS or isinstance(err, httpx.TransportError)
            if not transient or attempt == RETRIES - 1:
                raise
            time.sleep(2 ** (attempt + 1))
    raise RuntimeError("unreachable")


def synthesize(client, line: Line, speaker: dict, model: str, output_format: str) -> bytes:
    from elevenlabs import VoiceSettings

    stability = stability_for(line, speaker)
    settings = VoiceSettings(stability=stability) if stability is not None else None
    return _with_retries(lambda: client.text_to_speech.convert(
        voice_id=voice_id_from(speaker["voice_id"]), text=spoken_text(line, model), model_id=model,
        output_format=output_format, voice_settings=settings))


def make_sound(client, sound: Sound, output_format: str) -> bytes:
    return _with_retries(lambda: client.text_to_sound_effects.convert(
        text=sound.prompt, duration_seconds=float(sound.seconds), loop=sound.loop == "yes", prompt_influence=0.5,
        model_id=SFX_MODEL, output_format=output_format))


def _select(lines: list[Line], only: list[str]) -> list[Line]:
    if not only:
        return lines
    want = {w.lower() for w in only}
    return [ln for ln in lines if {ln.id.lower(), ln.scene.lower(), ln.speaker.lower()} & want]


def _select_sounds(sounds: list[Sound], only: list[str]) -> list[Sound]:
    if not only:
        return sounds
    want = {w.lower() for w in only}
    return sounds if "sfx" in want else [s for s in sounds if s.id.lower() in want]


def cmd_my_voices() -> None:
    client = _client()
    voices = client.voices.get_all().voices
    for v in sorted(voices, key=lambda v: (v.category or "", v.name or "")):
        print(f"  {v.voice_id}  {v.name}  ({v.category})")
    print(f"{len(voices)} voices. Paste IDs into audio/voices.json.")


def cmd_check(cast: dict, lines: list[Line]) -> None:
    client = _client()
    try:
        sub = client.user.subscription.get()
        left = (sub.character_limit or 0) - (sub.character_count or 0)
        print(f"Key works. Plan: {sub.tier}. Characters left this period: {left:,} of {sub.character_limit:,}.")
    except Exception as err:
        status, code, msg = _api_detail(err)
        sys.exit(f"The key was rejected ({status} {code}): {msg}")
    for name, sp in cast["speakers"].items():
        vid = voice_id_from(sp.get("voice_id", ""))
        count = sum(ln.speaker == name for ln in lines)
        if not vid:
            print(f"  {name:10} not cast yet ({count} lines)")
            continue
        try:
            print(f"  {name:10} {vid}  '{client.voices.get(vid).name}'  ({count} lines)")
        except Exception as err:
            _, code, msg = _api_detail(err)
            print(f"  {name:10} {vid}  NOT FOUND in your account ({code or msg}). If it's a Voice Library voice, open it on "
                  "elevenlabs.io and add it to My Voices, then check again.")
    print(f"ffmpeg for polishing: {_ffmpeg() or 'MISSING (pip install imageio-ffmpeg)'}")


def cmd_adopt(lines: list[Line], cast: dict, args: argparse.Namespace) -> int:
    """Records mp3s made elsewhere (the ElevenLabs app or connector, same voice and model) as current, so they aren't paid
    for again. They count as raw takes, so the next run polishes them. Without --only it adopts only files that have no
    record yet; with --only it re-adopts those lines."""
    model = args.model or cast.get("model", "eleven_v3")
    fmt = cast.get("output_format", "mp3_44100_128")
    old = read_manifest(args.out)
    hashes = {k: v["hash"] for k, v in old.items() if v.get("hash")}
    posts = {k: v.get("post", "") for k, v in old.items()}
    adopted = []
    for ln in _select(lines, args.only):
        sp = cast["speakers"][ln.speaker]
        if not (args.out / f"{ln.id}.mp3").exists() or not voice_id_from(sp.get("voice_id", "")):
            continue
        if not args.only and ln.id in hashes:
            continue
        hashes[ln.id], posts[ln.id] = line_hash(ln, sp, model, fmt), ""
        adopted.append(ln.id)
    write_manifest(lines, cast, args.out, hashes, posts, model)
    print(f"Adopted {len(adopted)} line(s): {' '.join(adopted) or '-'}")
    return 0


@dataclass
class Job:
    kind: str       # "line" or "sound"
    item: object    # Line or Sound
    hash: str
    post: str       # polish to apply ('' = none)
    call: bool      # True: generate with the API; False: only polish the raw file already on disk
    have: str = ""  # polish the file on disk already has
    adjust: dict | None = None  # a volume or level step applied to the polished take in place
    from_raw: bool = False      # restore this machine's raw take from .raw/ and polish it


def plan(lines: list[Line], sounds: list[Sound], cast: dict, args: argparse.Namespace, voice_old: dict,
         sfx_old: dict) -> tuple[list[Job], int, dict[str, int]]:
    """What this run has to do: generate new or changed items, and polish raw takes whose polish is missing."""
    model = args.model or cast.get("model", "eleven_v3")
    fmt = cast.get("output_format", "mp3_44100_128")
    jobs, cached, uncast = [], 0, {}

    def decide(kind, item, path, h, want, old):
        nonlocal cached
        have = old.get(item.id, {})
        fresh = not args.force and have.get("hash") == h and path.exists()
        done = have.get("post", "") if fresh else ""
        if fresh and done == want:
            cached += 1
        elif fresh and not done:
            jobs.append(Job(kind, item, h, want, call=False))  # raw take: polish it, no credits
        elif not args.force and raw_path(path, h).exists():
            jobs.append(Job(kind, item, h, want, call=False, have=done, from_raw=True))  # repolish this machine's raw take
        elif fresh and (step := in_place(done, want)) is not None:
            jobs.append(Job(kind, item, h, want, call=False, have=done, adjust=step))  # louder or quieter, no credits
        else:
            jobs.append(Job(kind, item, h, want, call=True))   # new, changed, or polished differently: regenerate

    for ln in _select(lines, args.only):
        sp = cast["speakers"][ln.speaker]
        if not voice_id_from(sp.get("voice_id", "")):
            uncast[ln.speaker] = uncast.get(ln.speaker, 0) + 1
            continue
        decide("line", ln, args.out / f"{ln.id}.mp3", line_hash(ln, sp, model, fmt), voice_post(sp), voice_old)
    if not args.no_sfx:
        for s in _select_sounds(sounds, args.only):
            decide("sound", s, args.sfx_out / f"{s.id}.mp3", sound_hash(s, fmt), sound_post(s), sfx_old)
    return jobs, cached, uncast


def cmd_generate(lines: list[Line], sounds: list[Sound], cast: dict, args: argparse.Namespace) -> int:
    model = args.model or cast.get("model", "eleven_v3")
    fmt = cast.get("output_format", "mp3_44100_128")
    speakers = cast["speakers"]
    voice_old, sfx_old = read_manifest(args.out), read_manifest(args.sfx_out, "sounds")
    hashes = {k: v["hash"] for k, v in voice_old.items() if v.get("hash")}
    posts = {k: v.get("post", "") for k, v in voice_old.items()}
    s_hashes = {k: v["hash"] for k, v in sfx_old.items() if v.get("hash")}
    s_posts = {k: v.get("post", "") for k, v in sfx_old.items()}

    jobs, cached, uncast = plan(lines, sounds, cast, args, voice_old, sfx_old)
    if getattr(args, "polish_only", False):
        left = [j for j in jobs if j.call]
        jobs = [j for j in jobs if not j.call]
        if left:
            print(f"--polish-only: leaving {len(left)} item(s) that need a new take: {' '.join(j.item.id for j in left)}")
    calls = [j for j in jobs if j.call]
    chars = sum(len(spoken_text(j.item, model)) for j in calls if j.kind == "line")
    n_lines, n_sounds = sum(j.kind == "line" for j in calls), sum(j.kind == "sound" for j in calls)
    for name, n in sorted(uncast.items()):
        print(f"skip: {name} has no voice_id in voices.json ({n} lines)")
    print(f"{n_lines} lines to generate ({chars:,} characters, model {model}), {n_sounds} sounds to generate, "
          f"{len(jobs) - len(calls)} takes to polish only; {cached} already up to date.")
    if args.dry_run:
        for j in jobs:
            what = spoken_text(j.item, model) if j.kind == "line" else j.item.prompt
            print(f"  {'gen ' if j.call else 'pol '} {j.item.id:22} {getattr(j.item, 'speaker', 'sfx'):10} {what}")
        return 0
    if jobs and any(j.post for j in jobs) and not _ffmpeg():
        print("WARNING: ffmpeg not found (pip install imageio-ffmpeg); takes will be saved unpolished.")

    def save_manifests():
        write_manifest(lines, cast, args.out, hashes, posts, model)
        if sounds:
            write_sfx_manifest(sounds, args.sfx_out, s_hashes, s_posts, fmt)

    if not jobs:
        save_manifests()
        return 0

    client = _client() if calls else None
    stop = threading.Event()  # a bad key or an empty quota stops everything
    dead: set[str] = set()     # speakers whose voice can't be found
    lock = threading.Lock()
    failed: list[str] = []

    def work(j: Job) -> None:
        item = j.item
        who = getattr(item, "speaker", "sfx")
        out_dir = args.out if j.kind == "line" else args.sfx_out
        path = out_dir / f"{item.id}.mp3"
        if stop.is_set() or who in dead:
            failed.append(f"{item.id}: skipped")
            return
        if j.call:
            try:
                audio = (synthesize(client, item, speakers[item.speaker], model, fmt) if j.kind == "line"
                         else make_sound(client, item, fmt))
            except Exception as err:
                status, code, msg = _api_detail(err)
                if status in (401, 403) or "api_key" in code or code in {"quota_exceeded", "missing_permissions"}:
                    stop.set()
                    failed.append(f"{item.id}: {code or status} {msg} (stopping)")
                elif j.kind == "line" and (code == "voice_not_found" or status == 404):
                    with lock:
                        dead.add(who)
                    failed.append(f"{item.id}: {who}'s voice was not found. If it's a Voice Library voice, add it to "
                                  "My Voices on elevenlabs.io")
                else:
                    failed.append(f"{item.id}: {status} {code} {msg}")
                return
            out_dir.mkdir(parents=True, exist_ok=True)
            tmp = out_dir / f".{item.id}.mp3.part"
            tmp.write_bytes(audio)
            os.replace(tmp, path)
            if j.post:  # keep the raw take on this machine, so a later polish change needs no new take
                raw_path(path, j.hash).parent.mkdir(exist_ok=True)
                raw_path(path, j.hash).write_bytes(audio)
        elif j.from_raw:
            shutil.copyfile(raw_path(path, j.hash), path)
        done_post = j.have if j.adjust else ""
        if j.post and _ffmpeg():
            try:
                if j.adjust:
                    polish(path, volume_db=j.adjust["volume_db"], level=j.adjust["level"])
                else:
                    polish_line(path, speakers[item.speaker]) if j.kind == "line" else polish_sound(path, item)
                done_post = j.post
            except Exception as err:  # keep the take as it was; the next run tries the polish again
                print(f"  polish failed for {item.id}: {err}")
        with lock:
            if j.kind == "line":
                hashes[item.id], posts[item.id] = j.hash, done_post
            else:
                s_hashes[item.id], s_posts[item.id] = j.hash, done_post
        print(f"  ok  {item.id:22} {who:10} {'generated' if j.call else 'polished'}{' + polished' if j.call and done_post else ''}")

    try:
        with ThreadPoolExecutor(max_workers=max(1, args.workers)) as pool:
            for fut in as_completed([pool.submit(work, j) for j in jobs]):
                fut.result()
    except KeyboardInterrupt:
        stop.set()
        print("Interrupted; keeping what finished.")
    finally:
        save_manifests()

    print(f"Done {len(jobs) - len(failed)} of {len(jobs)} jobs.")
    for f in failed:
        print("  FAILED " + f)
    return 1 if failed else 0


def orphans(lines: list[Line], sounds: list[Sound], args: argparse.Namespace) -> list[Path]:
    """mp3s on disk whose line or sound was removed from the bank."""
    out = [p for p in args.out.glob("*.mp3") if p.stem not in {ln.id for ln in lines}]
    return out + [p for p in args.sfx_out.glob("*.mp3") if p.stem not in {s.id for s in sounds}]


def main(argv: list[str] | None = None) -> int:
    p = argparse.ArgumentParser(description=__doc__.split("\n\n")[0])
    p.add_argument("--dry-run", action="store_true", help="validate and list what would be generated; no key, no API calls")
    p.add_argument("--check", action="store_true", help="check the key, the cast voices and the characters left")
    p.add_argument("--my-voices", action="store_true", help="list the voices in your ElevenLabs account")
    p.add_argument("--manifest-only", action="store_true", help="rewrite the manifests from the files on disk")
    p.add_argument("--adopt", action="store_true", help="count mp3s made in the ElevenLabs app or connector as up to date")
    p.add_argument("--prune", action="store_true", help="delete mp3s whose line or sound is no longer in the bank")
    p.add_argument("--only", nargs="+", default=[], metavar="WHAT", help="scene, speaker, line or sound id, or 'sfx'")
    p.add_argument("--force", action="store_true", help="regenerate even if up to date")
    p.add_argument("--no-sfx", action="store_true", help="skip the sound effects")
    p.add_argument("--polish-only", action="store_true", help="no key needed: apply polish changes, skip anything that "
                   "needs a new take")
    p.add_argument("--model", default="", help="override the model in voices.json (e.g. eleven_multilingual_v2)")
    p.add_argument("--workers", type=int, default=2, help="parallel requests (keep within your plan's concurrency)")
    p.add_argument("--out", type=Path, default=OUT_DIR, help="voice output folder (default audio/voice)")
    p.add_argument("--sfx-out", type=Path, default=SFX_DIR, help="sound output folder (default audio/sfx)")
    args = p.parse_args(argv)
    args.out, args.sfx_out = args.out.resolve(), args.sfx_out.resolve()

    lines, cast, sounds = load_lines(), load_cast(), load_sounds()
    bad = problems(lines, cast, sounds)
    if bad:
        print("Fix these in audio/lines.csv, audio/sfx.csv or audio/voices.json first:")
        print("\n".join("  " + b for b in bad))
        return 2
    if args.my_voices:
        cmd_my_voices()
        return 0
    if args.check:
        cmd_check(cast, lines)
        return 0
    if args.adopt:
        return cmd_adopt(lines, cast, args)
    stale = orphans(lines, sounds, args)
    if args.prune:
        for path in stale:
            path.unlink()
        print(f"Deleted {len(stale)} file(s) no longer in the bank: {' '.join(p.name for p in stale) or '-'}")
        stale = []
    elif stale:
        print(f"note: {len(stale)} mp3(s) are no longer in the bank (--prune deletes them): "
              f"{' '.join(p.name for p in stale)}")
    if args.manifest_only:
        old, s_old = read_manifest(args.out), read_manifest(args.sfx_out, "sounds")
        write_manifest(lines, cast, args.out, {k: v["hash"] for k, v in old.items() if v.get("hash")},
                       {k: v.get("post", "") for k, v in old.items()}, args.model)
        if sounds:
            write_sfx_manifest(sounds, args.sfx_out, {k: v["hash"] for k, v in s_old.items() if v.get("hash")},
                               {k: v.get("post", "") for k, v in s_old.items()}, cast.get("output_format", "mp3_44100_128"))
        print(f"Manifests written for {len(lines)} lines and {len(sounds)} sounds.")
        return 0
    return cmd_generate(lines, sounds, cast, args)


if __name__ == "__main__":
    sys.exit(main())
